# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('courses', models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('Mech', 'Mech'), ('Aero', 'Aero'), ('BioTech', 'BioTech')], default='CSE', max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
    ]
